# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

# example_temperature_curve:
#   # range of temperatures for which this linear function applies
# - range: [0, 65]
#     # range of values in this temperature range, can be undefined if
#     # measuring pwm is not supported on given platform
#   evaluation_pwm: [20, 25]
#     # range of values in this temperature range, can be undefined if
#     # measuring pwm is not supported on given platform
#     # accepted tolerance of pwm values - by how much can it differ from the
#     # expected value
#   tolerance_pwm: 6
#   evaluation_rpm: [0, 3000]
#     # accepted tolerance of rpm values - by how much can it differ from the
#     # expected value
#   tolerance_rpm: 100
#     # Next linear function for next temperature range. The temperature ranges
#     # must not overlap and be sorted in an ascending order
# - range: [65, 70]
#   evaluation_pwm: [25, 35]
#   tolerance_pwm: 6
#   evaluation_rpm: [0, 3000]
#   tolerance_rpm: 100

temperature_curve_silent:
  - range: [0, 65]
    evaluation_pwm: [20, 25]
    tolerance_pwm: 6
    evaluation_rpm: [0, 0]
    tolerance_rpm: 10000

  - range: [65, 75]
    evaluation_pwm: [25, 35]
    tolerance_pwm: 6
    evaluation_rpm: [0, 0]
    tolerance_rpm: 10000

  - range: [75, 100]
    evaluation: [35, 100]
    tolerance_pwm: 6
    evaluation_rpm: [0, 0]
    tolerance_rpm: 10000

temperature_curve_performance:
  - range: [0, 55]
    evaluation_pwm: [25, 35]
    tolerance_pwm: 6
    evaluation_rpm: [0, 0]
    tolerance_rpm: 10000

  - range: [55, 75]
    evaluation_pwm: [35, 60]
    tolerance_pwm: 6
    evaluation_rpm: [0, 0]
    tolerance_rpm: 10000

  - range: [75, 100]
    evaluation_pwm: [60, 100]
    tolerance_pwm: 6
    evaluation_rpm: [0, 0]
    tolerance_rpm: 10000

temperature_curve_off:
  - range: [0, 100]
    evaluation_pwm: [0, 0]
    tolerance_pwm: 100
    evaluation_rpm: [0, 0]
    tolerance_rpm: 10000
