# SPDX-FileCopyrightText: 2025 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

sensors_requirements_commands:
  - which sensors || (apt-get update && apt-get -y install lm-sensors)

sensors_prepare_commands:
  - sensors-detect --auto

cpu_temperature_measurement:
  gather: sensors dasharo_acpi-isa-0000 2>/dev/null
  filter: awk -F '[+°]' '/Package id 0:/ {print $2}'
  postprocess: cut -d. -f1

fan_rpm_measurement:
  gather: sensors dasharo_acpi-isa-0000 2>/dev/null
  filter: grep fan1 | tr -s ' ' | cut -d ' ' -f2
  postprocess:

# fan_pwm_measurement absent = unsupported
