# SPDX-FileCopyrightText: 2025 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

sensors_requirements_commands:
  "201": [ which sensors || (apt update && apt -y install lm-sensors) ]
  "202": [ which sensors || dnf -y install lm_sensors ]

sensors_prepare_commands:
  - sensors-detect --auto

cpu_temperature_measurement:
  gather: sensors dasharo_acpi-isa-0000 2>/dev/null
  filter: grep "CPU Package 0" | grep -oE "[0-9]+\.[0-9]+"
  postprocess: cut -d. -f1

fan_rpm_measurement:
  gather: sensors dasharo_acpi-isa-0000 2>/dev/null
  filter: grep RPM | grep "CPU 0" | tr -s ' ' | cut -d ' ' -f3
  postprocess:
