# SPDX-FileCopyrightText: 2025 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0
temperature_curve_settings:
  percentile_drop: 10
  acceptable_invalid_percent: 10

temperature_curve_silent:
  - range: [0, 55]
    evaluation_rpm: [2000, 2000]
    tolerance_rpm: 500 # anywhere between 1500 and 2500 is acceptable for <50C
  - range: [55, 75]
    evaluation_rpm: [2000, 3000]
    tolerance_rpm: 500 # at 50C [1500, 2500], at 62.5C [2000, 3000], at 75C [2500, 3500]
  - range: [75, 80]
    evaluation_rpm: [3000, 5000]
    tolerance_rpm: 500  # at 70C [2500, 3500], at 75C [3500, 4500], at 80C [4500, 5500]
  - range: [80, 100]
    evaluation_rpm: [6500, 6500]
    tolerance_rpm: 1500  # at 80C+ 5000-8000

temperature_curve_performance: # TODO - Its a COPY of SILENT - create actual curve for performance
  - range: [0, 55]
    evaluation_rpm: [2000, 2000]
    tolerance_rpm: 500 # anywhere between 1500 and 2500 is acceptable for <50C
  - range: [55, 75]
    evaluation_rpm: [2000, 3000]
    tolerance_rpm: 500 # at 50C [1500, 2500], at 62.5C [2000, 3000], at 75C [2500, 3500]
  - range: [75, 80]
    evaluation_rpm: [3000, 5000]
    tolerance_rpm: 500  # at 70C [2500, 3500], at 75C [3500, 4500], at 80C [4500, 5500]
  - range: [80, 100]
    evaluation_rpm: [6500, 6500]
    tolerance_rpm: 1500  # at 80C+ 5000-8000
