# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

cpu_temperature_measurement:
  method: lm-sensors
  hwmon_path: none
  lm_sensors_sensor_name: none

fan_pwm_measurement:
  method: none
  hwmon_path: none
  lm_sensors_sensor_name: none

fan_rpm_measurement:
  method: lm-sensors
  hwmon_path: none
  lm_sensors_sensor_name: it8786-isa-0a20

sensors_kernel_modules:
  - module: it87
    force_id: '0x8786'
