# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

sensors_requirements_commands:
  ubuntu: [ which sensors || (apt update && apt -y install lm-sensors) ]
  fedora: [ which sensors || dnf -y install lm_sensors ]

sensors_prepare_commands:
  - modprobe it87 force_id=0x8786
  - sensors-detect --auto

cpu_temperature_measurement:
  gather: sensors 2>/dev/null
  filter: awk -F '[+°]' '/Package id 0:/ {print $2}'
  postprocess: cut -d. -f1

fan_rpm_measurement:
  gather: sensors it8786-isa-0a20 2>/dev/null
  filter: grep fan1 | tr -s ' ' | cut -d ' ' -f2
  postprocess:
