# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: MIT

---
policies:
  - type: commit
    spec:
      header:
        length: 80
        imperative: false
        invalidLastCharacters: .
      body:
        required: false
      dco: true
      gpg:
        required: true
      spellcheck:
        locale: US
      maximumOfOneCommit: false
