# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

---
default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

ci:
  autoupdate_commit_msg: 'pre-commit: autoupdate hooks'
  autofix_prs: false
  # shellcheck requires docker, which is not available on pre-commit.ci
  skip: [shellcheck]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.30
    hooks:
      - id: conform
        stages:
          - commit-msg

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        exclude: ^scripts/freebsd/
        args: ["--severity=warning"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/MarketSquare/robotframework-robocop
    rev: v6.5.0
    hooks:
      - id: robocop
        additional_dependencies:
          - typing_extensions
      - id: robocop-format
        additional_dependencies:
          - typing_extensions

  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file
        exclude: ^dts/profiles

  - repo: local
    hooks:
      - id: platform-configs-var-check
        name: platform-configs
        description: Check for unused variables in platform-configs
        language: script
        entry: ./scripts/check-unused-variables.sh
        args: [ "-f" ]
        files: 'platform-configs/.*\.robot$'

      - id: test-ids-check
        name: test-ids-check
        description: Check if test IDs are valid
        language: python
        additional_dependencies:
          - robotframework
          - fire
        entry: ./scripts/ci/test_ids/test_ids_legal.py
        args: ["id_valid", "--print_invalid"]
        files: '^dasharo-.*/.*\.robot$'
        pass_filenames: false

      - id: test-os-ids-check
        name: test-os-ids-check
        description: Check if OS ids in tests are valid
        language: python
        additional_dependencies:
          - robotframework
          - fire
        entry: ./scripts/ci/test_ids/test_ids_legal.py
        args: ["os_valid", "--print_invalid"]
        files: '^dasharo-.*/.*\.robot$'
        pass_filenames: false
        # disable from automatic runs until we fix IDs
        stages: [manual]

      - id: test-ids-mappings
        name: test-ids-mappings
        description: Check if test IDs are mappped correctly in test_cases.json
        language: python
        additional_dependencies:
          - robotframework
          - fire
        entry: ./scripts/ci/test_ids/test_ids_legal.py
        args: ["id_mapped", "--print_invalid"]
        files: '(^test_cases\.json$|^dasharo-.*/.*\.robot$)'
        pass_filenames: false
        # disable from automatic runs until we fix IDs
        stages: [manual]

      - id: test-os-skip-check
        name: test-os-skip-check
        description: Check that OS tests have OS-support Skips and only OS tests have them
        language: python
        additional_dependencies:
          - robotframework
          - fire
        entry: ./scripts/ci/test_ids/test_ids_legal.py
        args: ["os_skip_valid", "--print_invalid"]
        files: '^dasharo-.*/.*\.robot$'
        pass_filenames: false

      - id: test-docs-match
        name: test-docs-match
        description: Check that all tests in docs-dasharo are implemented in robot code
        language: python
        additional_dependencies:
          - robotframework
          - fire
        entry: ./scripts/ci/test_ids/test_ids_legal.py
        args: ["docs_match", "--print_invalid"]
        files: '(^dasharo-.*/.*\.robot$|^docs-dasharo/.*\.md$)'
        pass_filenames: false

      - id: test-names-match
        name: test-names-match
        description: Check that test names in robot code match names in test_cases.json
        language: python
        additional_dependencies:
          - robotframework
          - fire
        entry: ./scripts/ci/test_ids/test_ids_legal.py
        args: ["names_match", "--print_invalid"]
        files: '(^test_cases\.json$|^dasharo-.*/.*\.robot$)'
        pass_filenames: false

      - id: test-ids-sort
        name: test-ids-sort
        description: Check if test_ids.json is sorted, and fix it
        language: python
        entry: ./scripts/ci/test_ids/check_sort.py
        args: ["--fix"]
        files: '^test_cases\.json$'

      - id: check-platform-config-vars
        name: Check Platform Config Variables
        description: Check if platform config file define variables not present in include/default.robot
        language: python
        additional_dependencies:
          - robotframework
        entry: ./scripts/ci/check_platform_configs_vars.py
        args: []
        files: '^.*\.robot$'
        pass_filenames: false
