# SPDX-FileCopyrightText: 2025 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

- name: geerlingguy.docker
  src: https://github.com/geerlingguy/ansible-role-docker
  version: 7.8.0
