# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

[tool.robocop]
language = ["en"]

[tool.robocop.lint]

ignore = [
    # TODO: add missing documentation for keywords and re-enable
    "DOC01",
    # TODO: add missing documentation for test cases and re-enable
    "DOC02",
    # TODO: add missing documentation for test suitdes and re-enable
    "DOC03",
    # TODO: consider re-enabling
    "NAME01",
    # TODO: consider fixing and re-enabling
    "VAR08",
    # TODO: fix and re-enable
    "DEPR02",
    # TODO: fix and re-enable
    "DEPR05",
    # TODO: fix and re-enable
    "DEPR06",

    # TODO: fix and re-enable
    "COM01",
    # TODO: fix and re-enable
    "DEPR01",
    # TODO: re-enable after fixes
    "MISC06",
    # TODO: fix unused variables and re-enable
    "VAR02",
    # TODO: consider fixing and re-enabling
    "VAR03",
    # TODO: fix and re-enable
    "MISC13",

    # TODO: fix and re-enable
    "ARG01",
    # TODO: fix and re-enable
    "VAR04",
    # TODO: fix and re-enable
    "VAR05",
    # TODO: fix and re-enable
    "VAR06",
    # TODO: fix and re-enable
    "LEN27"
]

configure = [
    # TODO: consider reducing to default 40, or less
    # Has to be high to allow comprehensive documentation of library keywords
    "too-long-keyword.max_len=80",
    # TODO: consider reducing to default 10, or less
    "too-many-calls-in-keyword.max_calls=50",
    # TODO: consider reducing to dfeault 20, or less
    "too-long-test-case.max_len=50",
    # TODO: consider reducing to dfeault 10, or less
    "too-many-calls-in-test-case.max_calls=50",
    # TODO: reduce to default 400 or so
    "file-too-long.max_lines=5000",
    # TODO: reduce to 120/80
    "line-too-long.line_length=180",
]
