# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

package_network_manager: NetworkManager
package_lm_sensors: lm_sensors
package_flashrom: flashrom
package_pciutils: pciutils
package_libpci_dev: pciutils-devel
package_alsa_utils: alsa-utils
package_cpuid: cpuid
package_dmidecode: dmidecode
package_acpi_call: bash # TODO, not available in dnf?
package_libinput_tools: libinput-utils
package_iperf3: iperf3
package_fwts: fwts
package_util_linux: util-linux
package_smartmontools: smartmontools
package_ffmeg: ffmpeg
package_usbutils: usbutils
package_tpm2_tools: tpm2-tools
package_ethtool: ethtool
package_stress_ng: stress-ng
package_pulseaudio_utils: pulseaudio-utils
