# SPDX-FileCopyrightText: 2026 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

version: '3'

includes:
  docker:
    taskfile: ../../taskfile-templates/templates/common/docker-run.yml
    optional: true

vars:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel
  QEMU_IMAGE_NAME: ghcr.io/dasharo/osfv-qemu-ci
  QEMU_IMAGE: '{{.QEMU_IMAGE_NAME}}:latest'

tasks:
  main:
    desc: Run keywords self-tests with QEMU
    dir: '{{.REPO_ROOT}}'
    cmds:
      - task: '{{if .CI}}run:local{{else}}run:container{{end}}'

  run:local:
    desc: Run the QEMU self-tests in the current environment, no container
    dir: '{{.REPO_ROOT}}'
    cmds:
      - bash .ci/qemu-self-test.sh

  run:container:
    desc: Run the QEMU self-tests inside {{.QEMU_IMAGE}}
    dir: '{{.REPO_ROOT}}'
    cmds:
      - task: docker:run
        vars:
          IMAGE: '{{.QEMU_IMAGE}}'
          DOCKER_ARGS: --device /dev/kvm
          VOLUMES: '{{.REPO_ROOT}}:/workspace'
          WORKDIR: /workspace
          COMMAND: bash .ci/qemu-self-test.sh

  stress:main:
    desc: Run keywords stress-tests with QEMU
    dir: '{{.REPO_ROOT}}'
    cmds:
      - task: '{{if .CI}}stress:run:local{{else}}stress:run:container{{end}}'

  stress:run:local:
    desc: Run the QEMU stress-tests in the current environment, no container
    dir: '{{.REPO_ROOT}}'
    env:
      STRESS: 1
    cmds:
      - bash .ci/qemu-self-test.sh

  stress:run:container:
    desc: Run the QEMU stress-tests inside {{.QEMU_IMAGE}}
    dir: '{{.REPO_ROOT}}'
    cmds:
      - task: docker:run
        vars:
          IMAGE: '{{.QEMU_IMAGE}}'
          DOCKER_ARGS: --device /dev/kvm
          ENV: STRESS=1
          VOLUMES: '{{.REPO_ROOT}}:/workspace'
          WORKDIR: /workspace
          COMMAND: bash .ci/qemu-self-test.sh
