# SPDX-FileCopyrightText: 2026 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

version: '3'

vars:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel
  QEMU_IMAGE_NAME: ghcr.io/dasharo/osfv-qemu-ci
  QEMU_IMAGE: '{{.QEMU_IMAGE_NAME}}:latest'

tasks:
  main:
    desc: Run keywords self-tests with QEMU
    dir: '{{.REPO_ROOT}}'
    cmds:
      - task: '{{if .CI}}run:local{{else}}run:container{{end}}'

  run:local:
    desc: Run the QEMU self-tests in the current environment, no container
    dir: '{{.REPO_ROOT}}'
    cmds:
      - bash .ci/qemu-self-test.sh

  run:container:
    desc: Run the QEMU self-tests inside {{.QEMU_IMAGE}}
    dir: '{{.REPO_ROOT}}'
    cmds:
      - |
        docker run --rm \
        --device /dev/kvm \
        -v {{.REPO_ROOT}}:/workspace \
        -w /workspace \
        {{.QEMU_IMAGE}} bash .ci/qemu-self-test.sh
