# SPDX-FileCopyrightText: 2025 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

name: 'Setup git-annex and test-data repo'
description: 'Sets git-annex and test-data repo'
runs:
  using: 'composite'
  steps:
    - name: Set up git-annex
      shell: bash
      run: |
         sudo apt-get install git-annex

    - name: Set up osfv-test-data
      working-directory: osfv-test-data
      shell: bash
      run: |
        set +e
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git annex pull
        ./setup.sh
