# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

- name: Prepare UEFI Shell components
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: /tmp/
    mode: 755
  loop:
    - src: "./../../../osfv-test-data/uefi-shell/Shell.efi"
    - src: "./../../../osfv-test-data/uefi-shell/deploy-shell-efi.sh"

- name: Make python3 accessible as python
  ansible.builtin.package:
    update_cache: true
    name:
      - python-is-python3
    state: present
