# SPDX-FileCopyrightText: 2026 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

- name: Common tasks
  hosts: host
  become: true
  tasks:
    - name: Systemwide update
      include_tasks: tasks/system_update.yml
    - name: Load package names
      ansible.builtin.include_vars: "{{os_id}}-packages.yaml"
    - name: Install packages
      ansible.builtin.package:
        update_cache: true
        name:
          - "{{package_network_manager}}"
          - "{{package_lm_sensors}}"
          - "{{package_flashrom}}"
          - "{{package_libpci_dev}}"
          - "{{package_alsa_utils}}"
          - "{{package_cpuid}}"
          - "{{package_dmidecode}}"
          - "{{package_acpi_call}}"
          - "{{package_libinput_tools}}"
          - "{{package_iperf3}}"
          - "{{package_fwts}}"
          - "{{package_util_linux}}"
          - "{{package_smartmontools}}"
          - "{{package_ffmeg}}"
          - "{{package_usbutils}}"
          - "{{package_tpm2_tools}}"
          - "{{package_pulseaudio_utils}}"
        state: present
    - name: Install coreboot tools files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: /usr/bin/
        mode: 755
      loop:
        - src: "./../../osfv-test-data/coreboot-tools/flashrom"
        - src: "./../../osfv-test-data/coreboot-tools/cbmem"
        - src: "./../../osfv-test-data/coreboot-tools/cbfstool"

    - name: Gnome turn off automatic suspend on AC
      ansible.builtin.command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0
      ignore_errors: true
    - name: Gnome turn off automatic suspend on battery
      ansible.builtin.command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 0
      ignore_errors: true
    - name: Gnome turn off automatic screen lock
      ansible.builtin.command: gsettings set org.gnome.desktop.session idle-delay 0
    - name: Install docker
      import_role:
        name: geerlingguy.docker

- name: OS specific tasks
  hosts: host
  become: true
  tasks:
    - name: Include OS specific tasks
      ansible.builtin.include_tasks: "os-specific-tasks/{{ os_id }}.yaml"
