# SPDX-FileCopyrightText: 2026 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

# Only try to run if a robot file or a lib was modified in the PR
when:
  - branch: develop
    event: [pull_request, manual]
    path:
      include:
        - '*.robot'
        - '**/*.robot'
        - lib/**
        - .ci/develop-pr-regression.sh
        - .ci/Dockerfile.qemu
        - .woodpecker/develop-pr-regression.yml

labels:
  network: office

# One workflow per device, so that every device reports its own status and a
# device failing does not hide the results of the others
matrix:
  DEVICE:
    - msi-pro-z690-a-wifi-ddr4_00039
    # - novacustom-nuc_box-125H_00245
    # - novacustom-nuc_box-155H_00254
    # - novacustom-v540tnd_00266
    # - novacustom-v540tu_00191
    - pcengines-apu3_00252
    # - protectli-vp2410_00052
    # - protectli-vp6650_00002

concurrency:
  limit: 1
  group: device-${DEVICE} # only one job will work on one device from the matrix

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false
      # The regression scope is a diff against the base branch
      partial: false
      depth: 0

steps:
  - name: regression
    image: ghcr.io/dasharo/osfv-qemu-ci:latest
    pull: true
    environment:
      SNIPEIT_CONFIG:
        from_secret: SNIPEIT_YAML_CONFIG_FILE
      BASE_BRANCH: ${CI_COMMIT_TARGET_BRANCH}
      NFS_IP:
        from_secret: OSFV_NFS_IP
      OSFV_ROMS_DIR: /srv/nfs/roms
    privileged: true
    commands:
      - mkdir -p /srv/nfs/roms
      - mount -t nfs -o nolock,ro "$${NFS_IP}":/srv/nfs/roms /srv/nfs/roms
      - mountpoint -q /srv/nfs/roms
      - TASK_X_REMOTE_TASKFILES=1 task --yes --taskfile .ci/Taskfile.yml ci:develop-pr-regression DEVICE="$DEVICE"

  - name: check-in # make sure its checked in even if the task fails
    image: ghcr.io/dasharo/osfv-qemu-ci:latest
    environment:
      SNIPEIT_CONFIG:
        from_secret: SNIPEIT_YAML_CONFIG_FILE
    commands:
      - mkdir -p "/root/.osfv"
      - printf '%s\n' "$${SNIPEIT_CONFIG}" > "/root/.osfv/snipeit.yml"
      - osfv_cli snipeit check_in --asset_id "$${DEVICE##*_}" || true
    when:
      - status: [success, failure]
