# SPDX-FileCopyrightText: 2026 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

when:
  - branch: [develop, main]
    event: [pull_request, push, manual]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false
      partial: false
      depth: 0

steps:
  - name: pre-commit
    image: ghcr.io/dasharo/osfv-ci:latest
    commands:
      - TASK_X_REMOTE_TASKFILES=1 task --yes --taskfile .ci/Taskfile.yml ci:pre-commit
