# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Smoke tests on selected platforms

# Only try to run if a robot file or a lib was modified in the PR
on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.robot'
      - 'lib/**'

concurrency:
  group: shared-resource-lock
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: ./.github/actions/setup-common
      - uses: ./.github/actions/setup-python

      - name: Execute robot command
        run: |
          scripts/ci/develop_pr_auto_regression.sh

      - name: Upload HTML files as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: HTML-Reports
          path: |
            logs/
