# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Smoke tests on selected platforms

# Only try to run if a robot file or a lib was modified in the PR
on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.robot'
      - 'lib/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: check network
      run: |
        ip a
        ping -c 3 192.168.10.1
        ping -c 3 192.168.4.1
        ping -c 3 1.1.1.1

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Fetch develop branch
      run: git fetch origin develop

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute robot command
      run: |
        scripts/ci/develop_pr_auto_regression.sh

    - name: Upload HTML files as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: HTML-Reports
        path: |
          logs/
