# SPDX-FileCopyrightText: 2026 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

name: OSFV Regression managed by scripts instead of actions

# Only try to run if a robot file or a lib was modified in the PR
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 6 * * 6' # Every week, 6 AM on Saturday

env:
  ALLOW_DIRTY: 1

concurrency:
  group: naive_osfv_regression
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        clean: true

    - name: Chceckout submodules
      run: |
        git submodule update --init --checkout --recursive

    - name: Fetch develop branch
      run: git fetch origin develop

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install uv
        rm -rf venv
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        deactivate
        source venv/bin/activate

    - name: Run tests
      run: |
        scripts/ci/osfv_stability_run.py

    - name: Create report
      run: |
        scripts/ci/osfv_stability_reports.py | tee report.txt

    - name: Upload HTML files as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: HTML-Reports
        path: |
          ci-logs/

    - name: Upload report as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: HTML-Reports
        path: |
          report.txt
