# SPDX-FileCopyrightText: 2026 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

name: pre-commit

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dasharo/osfv-ci:latest
    steps:
      - uses: actions/checkout@v4
        with:
          python-version:  3.14
          fetch-depth: 0
      - run: TASK_X_REMOTE_TASKFILES=1 task --yes --taskfile .ci/Taskfile.yml ci:pre-commit
