# SPDX-FileCopyrightText: 2025 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Pre-commit checks

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: ./.github/actions/setup-common

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.sha }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version:  3.13

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args:
            --all-files
