name: Keywords self-tests with QEMU

on: [push, pull_request]

jobs:
  qemu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up QEMU
      run: |
         sudo apt-get update
         sudo apt-get install qemu-system-x86-64

    - name: Start QEMU in background
      run: |
        ./scripts/ci/qemu-run.sh nographic &

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start keywords self-tests with QEMU
      run: |
        ./scripts/ci/qemu-self-test.sh
