# SPDX-FileCopyrightText: 2025 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Keywords self-tests with QEMU

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'lib/**'
      - 'keywords.robot'
      - '.github/workflows/qemu-self-test.yml'
      - 'scripts/ci/qemu-self-test.sh'
      - 'scripts/ci/qemu-run.sh'
      - 'requirements.txt'

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: ./.github/actions/setup-common
      - uses: ./.github/actions/setup-qemu
      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/setup-test-data

      - name: Start keywords self-tests with QEMU
        run: |
          ./scripts/ci/qemu-self-test.sh

      - name: Save artifacts
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: "qemu-logs"
          path: |
             ./logs/
          retention-days: 30
